### ISSUE TITLE
Formatted links require confirmation on click

### ISSUE THREAD

**Issue by dermyrddin** [phil-r/hackernewsbot#1]
When you click on the news header, telegram ask for confirmation like this http://prntscr.com/ctlm4u
This is very annoying :(

Possible solution is to place link after title:
Show HN: Marathono – A GUI tool for managing long-running processes in macOS
Link: http://www.marathono.com
Score: 102+
Comments: 51+ https://news.ycombinator.com/item?id=12685780

**Comment by phil-r** [comment]
Hello @merlineus, thanks for your comment
I think you are right, I'll fix it today ;)

**Comment by dermyrddin** [comment]
Thank you )

Maybe title will be more readable if you move "Score" to the new line?

**Comment by dermyrddin** [comment]
Here is how message looks for russian site habrahabr.ru (https://telegram.me/tmfeed):

**Intel will add to the CPU instructions for deep learning**
https://geektimes.ru/post/281518/
**Tags:** Processors, Programming, Artificial Intelligence, deep learning, Intel, CPU, AVX-512
**Author:** [alizar](https://geektimes.ru/users/alizar) on #geektimes

**Comment by phil-r** [comment]
@merlineus 
What about this format:

---

**KiCad: A commitment to freedom**

https://giving.web.cern.ch/content/kicad-development-1
**Score:** 139+
**37+ Comments:** https://news.ycombinator.com/item?id=12713089

---
