### ISSUE TITLE
Red cross

### ISSUE THREAD

**Issue by maxgashkov** [phil-r/hackernewsbot#28]
Hi,

What is the purpose of the red cross in telegram channel's name?

<img width="625" alt="Screenshot 2020-07-02 09 46 07" src="https://user-images.githubusercontent.com/1167090/86304152-f6a69180-bc48-11ea-96b0-83ac1a7b103d.png">

This looks incredibly disruptive in the chat list and, in contrast to usual human contacts, it's impossible to edit channel title to one's liking.

**Comment by phil-r** [comment]
Cross was removed
