### ISSUE TITLE
How do I run it on pycharm?

### ISSUE THREAD

**Issue by invasionofsmallcubes** [phil-r/hackernewsbot#30]
Hi,
how do I run it on pycharm? It's breaking because of Google App Engine dependencies missing.

Thanks,
Ema

**Comment by phil-r** [comment]
pycharm is an IDE, so it should be the same as with any other editor, please follow those instructions: https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server

Also note, that this project is written in python 2.7 and that version of python is not supported anymore.

Any help [migrating to python 3](https://github.com/phil-r/hackernewsbot/issues/18) is welcome

**Comment by invasionofsmallcubes** [comment]
I meant to port it on python 3 but the standard layer of google app engine doesn't support python 3.

Yes I was able to run with `dev_appserver.py` but I'm not sure on how to run it with debug on.

**Comment by phil-r** [comment]
Sadly, I don't know how to run `dev_appserver.py` in debug mode 😢

**Comment by invasionofsmallcubes** [comment]
Ok I think I managed for python37 but not 38. Sadly could not solve the debug issue.

**Comment by invasionofsmallcubes** [comment]
Hey @phil-r, so I managed to move some of it to python 3 but I decided to drop the case. The reason for this is not because I don't want to be helpful of course but because unfortunatley the entire `google.app.engine` does not exists as a library and it's not just a matter to find a new library but for example memcache it doesn't work anymore, they allow only redis which is a paid solution. Honestly it's not worth to move as it requires infrastructural changes.

**Comment by phil-r** [comment]
Hi @invasionofsmallcubes , thanks for your time, and I completely agree with you on the matter.

**Comment by invasionofsmallcubes** [comment]
Your code gave me some ideas on how to make my both, so thank you for that :D

**Comment by phil-r** [comment]
haha, feel free to share when it's ready 🤗
