### ISSUE TITLE
Adjust 🔥 emoji to inflation

### ISSUE THREAD

**Issue by MRVDH** [phil-r/hackernewsbot#35]
The fire emoji was implemented around april/may 2019, when the top 100 stories average points (1 year moving average) was 110. Currently that number is 145[1].

It might be worth raising the current value of 100 to something like 120-150.

Great bot btw 👍 

[1] - https://instruments.digital/inflation-adjusted-hn/

**Comment by phil-r** [comment]
Hey! Good idea, I'll try to add it over the weekend
