### ISSUE TITLE
Incorrect article information

### ISSUE THREAD

**Issue by MRVDH** [phil-r/hackernewsbot#37]
For some reason one message (and maybe more?) shows up as 2 days old, but actually it's only a few hours old.

These images are taken within a minute of each other:
![image](https://user-images.githubusercontent.com/6686385/132501480-132dfa5b-bd75-414a-8b79-e7a1004c8fc5.png)
![image](https://user-images.githubusercontent.com/6686385/132501507-98e3974b-9d11-42bf-94e1-6f57dae31d03.png)

**Comment by phil-r** [comment]
@MRVDH thanks for reporting, but it seems to be a bug in [hacker news api](https://github.com/HackerNews/API), see `time` field in this response: https://hacker-news.firebaseio.com/v0/item/28431716.json it's `1630918181` and that's `Mon Sep 06 08:49:41 2021 UTC`

On hacker news site everything is even more weirder, if you go here: https://news.ycombinator.com/item?id=28431716 it says `5 days ago` and hovering shows `2021-09-06T08:49:41` but as of today it's 7 days ago!

<details>
<summary>Screenshot taken on 13 Sep</summary>

<img width="490" alt="image" src="https://user-images.githubusercontent.com/577316/133126574-f6bae78c-2367-4ed8-a3ce-531e88d3607f.png">

</details>

Weird problem 🤔 I've contacted hacker news team, hope they'll figure it out.

**Comment by phil-r** [comment]
Got a reply from HN:

> That's an artifact of HN's re-upping system. The system is described at https://news.ycombinator.com/item?id=26998308 and links back from there. About the timestamps, there are past explanations here: https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=by%3Adang%20timestamps&sort=byDate&type=comment. I hope that will make sense.

> Sorry for the confusion—I know it's weird but the alternative turns out to be even more confusing and we've never figured out how to square that circle.

Sadly I don't see any easy solution to this, so I'll close the issue
